# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5097c8ed07447adc8558931351a0f7a771f8feacea674208765a3c49db5785256be6b641831e5b2869603ed5faf7215bd029c6ce74c695672e9c94e40e5519e

test:
  secret_key_base: e700851ae33a0de55d4563e73aa19c4883df082a8edb103012630c82c940577bb9e9353e9c7a6b9ca61767476429e1716807af419ab3a8b3ca090bc7bf7fd7b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
